# Generated by Django 3.1.6 on 2021-02-17 17:43

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='django-backend-dev-private'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Object Upload')),
                ('name', models.TextField()),
            ],
        ),
    ]
